### ISSUE TITLE
make the underlines short.

### ISSUE THREAD

**Issue by MetaFomos** [FWC-Gecko/gecko-web#20]

**Comment by MetaFomos** [comment]
![Image](https://user-images.githubusercontent.com/80467882/208839460-075324eb-861d-40e5-8caf-e1feb7c21ee5.png)

**Comment by NAJI0329** [comment]
Done.
![image](https://user-images.githubusercontent.com/94976661/209065253-a6a57172-96eb-4405-8f64-80d91ab19f8f.png)
