### ISSUE TITLE
Add more blockchains

### ISSUE THREAD

**Issue by MetaFomos** [FWC-Gecko/gecko-web#27]

**Comment by MetaFomos** [comment]
Ethereum
Binance Smart Chain
Polygon
Fantom
Avalanche
Optimism
Arbitrium
Cronos
Gnosis
Tron

**Comment by NAJI0329** [comment]
![image](https://user-images.githubusercontent.com/94976661/209062347-75938a88-2241-4613-9c74-b457e4a049d2.png)
